# Generated by Django 2.2.9 on 2020-01-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendorclientmatrix',
            name='cv_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Client Vendor ID'),
        ),
        migrations.AddField(
            model_name='historicalvendorclientmatrix',
            name='cv_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Client Vendor Name'),
        ),
        migrations.AddField(
            model_name='vendorclientmatrix',
            name='cv_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Client Vendor ID'),
        ),
        migrations.AddField(
            model_name='vendorclientmatrix',
            name='cv_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Client Vendor Name'),
        ),
    ]
