# Generated by Django 2.2.9 on 2020-01-23 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorLocMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vlm_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loc_2_vn', to='core.Location', verbose_name='Location')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vn_2_loc', to='core.Vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Vendor Location Record',
                'verbose_name_plural': 'Vendor Location Records',
            },
        ),
        migrations.CreateModel(
            name='VendorClientMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_2_vn', to='core.Client', verbose_name='Client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vcm_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vn_2_client', to='core.Vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Vendor Client Record',
                'verbose_name_plural': 'Vendor Client Records',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVendorLocMatrix',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, verbose_name='Status')),
                ('created_on', models.DateTimeField(blank=True, editable=False, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(blank=True, editable=False, verbose_name='Updated On')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Location', verbose_name='Location')),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'historical Vendor Location Record',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVendorClientMatrix',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, verbose_name='Status')),
                ('created_on', models.DateTimeField(blank=True, editable=False, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(blank=True, editable=False, verbose_name='Updated On')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'historical Vendor Client Record',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
