# Generated by Django 2.2.9 on 2020-01-17 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVendorItem',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('item_number', models.CharField(max_length=100, verbose_name='Vendor Item Number')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('pack_count', models.CharField(max_length=50, verbose_name='Package Count')),
                ('status', models.CharField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, max_length=1, verbose_name='Status')),
                ('created_on', models.DateTimeField(blank=True, editable=False, verbose_name='created on')),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uom', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='UOM')),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'historical Vendor Item Data',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VendorItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_number', models.CharField(max_length=100, verbose_name='Vendor Item Number')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('pack_count', models.CharField(max_length=50, verbose_name='Package Count')),
                ('status', models.CharField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, max_length=1, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unitofmeasure', to=settings.AUTH_USER_MODEL, verbose_name='UOM')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor', to=settings.AUTH_USER_MODEL, verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Vendor Item Data',
                'verbose_name_plural': 'Vendor Item Data',
            },
        ),
        migrations.RemoveField(
            model_name='itemdata',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='itemdata',
            name='uom',
        ),
        migrations.RemoveField(
            model_name='itemdata',
            name='vendor',
        ),
        migrations.AddField(
            model_name='historicalunitofmeasure',
            name='description',
            field=models.CharField(default='Desc', max_length=150, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='description',
            field=models.CharField(default=1, max_length=150, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HistoricalItemData',
        ),
        migrations.DeleteModel(
            name='ItemData',
        ),
    ]
