# Generated by Django 2.2.9 on 2020-01-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalvendorclientmatrix_historicalvendorlocmatrix_vendorclientmatrix_vendorlocmatrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendor',
            name='num_locations',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Locations'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='num_locations',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Locations'),
        ),
    ]
