# Generated by Django 2.2.9 on 2020-01-17 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200117_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvendoritem',
            name='uom',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.UnitOfMeasure', verbose_name='UOM'),
        ),
        migrations.AlterField(
            model_name='historicalvendoritem',
            name='vendor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Vendor', verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_vendor', to='core.Vendor', verbose_name='Parent Vendor'),
        ),
        migrations.AlterField(
            model_name='vendoritem',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unitofmeasure', to='core.UnitOfMeasure', verbose_name='UOM'),
        ),
        migrations.AlterField(
            model_name='vendoritem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor', to='core.Vendor', verbose_name='Vendor'),
        ),
    ]
