# Generated by Django 2.2.9 on 2020-01-27 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import itembase.core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_vinevendorimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='VineVendorFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=itembase.core.models.vine_upload_user_directory_path)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
    ]
