# Generated by Django 2.2.9 on 2020-01-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vinevendorfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinevendorimport',
            name='source',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Item'),
        ),
    ]
