# Generated by Django 2.2.9 on 2020-01-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200117_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstype',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicaladdresstype',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicallocationaddress',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalvendoraddress',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalvendoritem',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='locationaddress',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='vendoraddress',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='vendoritem',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, verbose_name='Status'),
        ),
    ]
