# Generated by Django 2.2.9 on 2020-01-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200127_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinevendorimport',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created On'),
        ),
    ]
