# Generated by Django 2.2.9 on 2020-01-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200117_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendor',
            name='num_items',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Items'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='num_items',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Items'),
        ),
    ]
