# Generated by Django 2.2.9 on 2020-02-03 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200127_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstype',
            name='usage',
            field=models.CharField(choices=[('L', 'Location'), ('V', 'Vendor'), ('C', 'Client')], max_length=1, verbose_name='Use'),
        ),
        migrations.AlterField(
            model_name='historicaladdresstype',
            name='usage',
            field=models.CharField(choices=[('L', 'Location'), ('V', 'Vendor'), ('C', 'Client')], max_length=1, verbose_name='Use'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
