# Generated by Django 2.2.9 on 2020-01-19 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200119_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendoritem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendoritems', to='core.Vendor', verbose_name='Vendor'),
        ),
    ]
