# Generated by Django 2.2.9 on 2020-01-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200119_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalvendoritem',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Item Data'},
        ),
        migrations.AlterModelOptions(
            name='vendoritem',
            options={'verbose_name': 'Item Data', 'verbose_name_plural': 'Item Data'},
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalvendoritem',
            name='item_number',
            field=models.CharField(max_length=100, verbose_name='Item Number'),
        ),
        migrations.AlterField(
            model_name='vendoritem',
            name='item_number',
            field=models.CharField(max_length=100, verbose_name='Item Number'),
        ),
    ]
