# Generated by Django 2.2.9 on 2020-02-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200203_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresstype',
            name='usage',
        ),
        migrations.RemoveField(
            model_name='historicaladdresstype',
            name='usage',
        ),
    ]
