# Generated by Django 2.2.9 on 2020-01-20 16:54

from django.db import migrations, models
import itembase.core.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200120_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=itembase.core.models.client_logo_directory_path, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='logo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Image'),
        ),
    ]
