# Generated by Django 2.2.9 on 2020-02-03 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20200203_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_on', models.CharField(choices=[('L', 'Location'), ('V', 'Vendor'), ('C', 'Client')], default='V', max_length=1, verbose_name='Used on')),
                ('address1', models.CharField(max_length=255, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address 2')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, max_length=3, null=True, verbose_name='Country')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('primary', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.AddressType', verbose_name='Address Type')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_address', to='core.Client', verbose_name='Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_address_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_address', to='core.Location', verbose_name='Location')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_address', to='core.Vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAddress',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('used_on', models.CharField(choices=[('L', 'Location'), ('V', 'Vendor'), ('C', 'Client')], default='V', max_length=1, verbose_name='Used on')),
                ('address1', models.CharField(max_length=255, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address 2')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, max_length=3, null=True, verbose_name='Country')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('primary', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, verbose_name='Status')),
                ('created_on', models.DateTimeField(blank=True, editable=False, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(blank=True, editable=False, verbose_name='Updated On')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('address_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.AddressType', verbose_name='Address Type')),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Location', verbose_name='Location')),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'historical address',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='historicalvendoraddress',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='historicalvendoraddress',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalvendoraddress',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalvendoraddress',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='locationaddress',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='locationaddress',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='locationaddress',
            name='location',
        ),
        migrations.RemoveField(
            model_name='vendoraddress',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='vendoraddress',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vendoraddress',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='HistoricalLocationAddress',
        ),
        migrations.DeleteModel(
            name='HistoricalVendorAddress',
        ),
        migrations.DeleteModel(
            name='LocationAddress',
        ),
        migrations.DeleteModel(
            name='VendorAddress',
        ),
    ]
