# Generated by Django 2.2.9 on 2020-01-20 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_contact_historicalcontact_installbase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='partner',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='historicalcontact',
            old_name='partner',
            new_name='vendor',
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='created on'),
        ),
    ]
