# Generated by Django 2.2.9 on 2020-02-05 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20200203_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstaffmember',
            name='user_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='user_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_user', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
    ]
