# Generated by Django 2.2.9 on 2020-01-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200120_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Valid'), (3, 'Inactive')], default=1, max_length=1, verbose_name='Status'),
        ),
    ]
