# Generated by Django 2.2.9 on 2020-03-02 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200205_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='service_start',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Service Start'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='service_start',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Service Start'),
        ),
    ]
