# Generated by Django 2.2.9 on 2020-01-20 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20200120_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='feegroup',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='historicaladdresstype',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='historicalfeegroup',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='historicalholidaylist',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='historicallocation',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='historicallocationaddress',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='historicalstaffmember',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='historicalstaffroles',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='historicalstaffshift',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='historicalstafftitle',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='historicalsystemtype',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='historicalteammember',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='historicalvendoraddress',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='historicalvendoritem',
            name='created_on',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='holidaylist',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='locationaddress',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='staffroles',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='staffshift',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='stafftitle',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='systemtype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='vendoraddress',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='vendoritem',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.CreateModel(
            name='HistoricalClientSystem',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('have_access', models.BooleanField(default=True, verbose_name='Access?')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Client', verbose_name='Client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.System', verbose_name='System')),
            ],
            options={
                'verbose_name': 'historical Client System',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ClientSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('have_access', models.BooleanField(default=True, verbose_name='Access?')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_systems', to='core.Client', verbose_name='Client')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.System', verbose_name='System')),
            ],
            options={
                'verbose_name': 'Client System',
                'unique_together': {('client', 'system')},
            },
        ),
    ]
