# Generated by Django 2.2.9 on 2020-03-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200301_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='service_start',
            field=models.DateField(blank=True, null=True, verbose_name='Service Start'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='service_start',
            field=models.DateField(blank=True, null=True, verbose_name='Service Start'),
        ),
    ]
