# Generated by Django 2.2.9 on 2020-01-20 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200120_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalteammember',
            name='role',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'status': 2}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.StaffRoles', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='historicalteammember',
            name='staff',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'status': 2}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.StaffMember', verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.ForeignKey(limit_choices_to={'status': 2}, on_delete=django.db.models.deletion.PROTECT, to='core.StaffRoles', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'status': 2}, on_delete=django.db.models.deletion.PROTECT, to='core.StaffMember', verbose_name='Staff'),
        ),
    ]
