# Generated by Django 2.2.9 on 2020-03-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200301_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvendor',
            name='name1',
            field=models.CharField(max_length=50, verbose_name='Primary Name'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name1',
            field=models.CharField(max_length=50, verbose_name='Primary Name'),
        ),
    ]
